#!/bin/sh
COMMAND="$1"
shift

ENV_FILE="$(dirname "$0")/.env"
if [ -f "$ENV_FILE" ]; then
  . "$ENV_FILE"
else
  echo "Error: .env file not found."
  echo "Read how to configure it: https://github.com/Ezhkin-Kot/utilities/blob/master/server-utility/README.md"
  exit 1
fi

case "$COMMAND" in
  start)
    tailscale up

    ROUTER_IP=$(tailscale status | grep openwrt | awk '{print $1}')
    
    ssh root@$ROUTER_IP "etherwake -i br-lan $WOL_MAC"
    ;;
  connect|stop)
    SERVER_NAME="$DEFAULT_SERVER_NAME"
    USER="$DEFAULT_USER_NAME"
    PORT=""

    while getopts "s:u:p:" opt; do
      case "$opt" in
        s) SERVER_NAME="$OPTARG" ;;
        u) USER="$OPTARG" ;;
        p) PORT="$OPTARG" ;;
        \?)
          SCRIPT_NAME=$(basename "$0")
          echo "Usage: $SCRIPT_NAME $COMMAND [-s server_name] [-u user] [-p port]"
          exit 1
          ;;
      esac
    done

    tailscale up

    SERVER_IP=$(tailscale status | grep $SERVER_NAME | awk '{print $1}')

    if [ -z "$SERVER_IP" ]; then
      echo "Error: server '$SERVER_NAME' not found in Tailscale."
      exit 1
    fi

    if [ "$COMMAND" = "connect" ]; then
      if [ -z "$PORT" ]; then
        ssh $USER@$SERVER_IP
      else
        ssh $USER@$SERVER_IP -p "$PORT"
      fi
    else # stop
      if [ -z "$PORT" ]; then
        ssh $USER@$SERVER_IP "shutdown -h now"
      else
        ssh $USER@$SERVER_IP -p "$PORT" "shutdown -h now"
      fi
    fi
    ;;
  *)
    SCRIPT_NAME=$(basename "$0")
    echo "Usage:"
    echo "  $SCRIPT_NAME start"
    echo "  $SCRIPT_NAME stop"
    echo "  $SCRIPT_NAME connect [server_name] [-u user] [-p port]"
    exit 1
    ;;
esac

