#!/bin/sh

CPP_FILE="$1"
SCRIPT_NAME=$(basename "$0")

if [ -z "$CPP_FILE" ]; then
  echo "Usage: $SCRIPT_NAME <file.cpp>"
  exit 1
fi

if [ ! -f "$CPP_FILE" ]; then
  echo "File '$CPP_FILE' does not exist"
  exit 1
fi

case "$CPP_FILE" in
  *.cpp) ;;
  *)
    echo "File must be a .cpp"
    exit 1
    ;;
esac

EXECUTABLE_FILE="${CPP_FILE%.cpp}"

g++-15 "$CPP_FILE" -o "$EXECUTABLE_FILE"
if [ $? -ne 0 ]; then
  echo "Compilation failed"
  exit 1
fi

"./$EXECUTABLE_FILE"
